export const UPDATE_EMPLOYEES = "UPDATE_EMPLOYEES";

export const SHOW_DELETE_EMPLOYEE = "SHOW_DELETE_EMPLOYEE";
export const HIDE_DELETE_EMPLOYEE = "HIDE_DELETE_EMPLOYEE";
export const SHOW_EDIT_EMPLOYEE = "SHOW_EDIT_EMPLOYEE";
export const HIDE_EDIT_EMPLOYEE = "HIDE_EDIT_EMPLOYEE";