export const UPDATE_EMPLOYEES = "UPDATE_EMPLOYEES";

export const SHOW_DELETE_EMPLOYEE = "SHOW_DELETE_EMPLOYEE";
export const HIDE_DELETE_EMPLOYEE = "HIDE_DELETE_EMPLOYEE";

export const SHOW_EDIT_EMPLOYEE = "SHOW_EDIT_EMPLOYEE";
export const HIDE_EDIT_EMPLOYEE = "HIDE_EDIT_EMPLOYEE";

export const SHOW_REGISTER_EMPLOYEE = "SHOW_REGISTER_EMPLOYEE";
export const HIDE_REGISTER_EMPLOYEE = "HIDE_REGISTER_EMPLOYEE";

export const SHOW_EXPORT_EXCEL = "SHOW_EXPORT_EXCEL";
export const HIDE_EXPORT_EXCEL = "HIDE_EXPORT_EXCEL";

export const SHOW_CHECK_CARD = "SHOW_CHECK_CARD";
export const HIDE_CHECK_CARD = "HIDE_CHECK_CARD";