export const UPDATE_USER = "UPDATE_USER";

export const UPDATE_EMPLOYEES = "UPDATE_EMPLOYEES";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";

export const SHOW_EMPLOYEE_WORK_LOG = "SHOW_EMPLOYEE_WORK_LOG";
export const HIDE_EMPLOYEE_WORK_LOG = "HIDE_EMPLOYEE_WORK_LOG";

export const SHOW_DELETE_EMPLOYEE = "SHOW_DELETE_EMPLOYEE";
export const HIDE_DELETE_EMPLOYEE = "HIDE_DELETE_EMPLOYEE";

export const SHOW_EDIT_EMPLOYEE = "SHOW_EDIT_EMPLOYEE";
export const HIDE_EDIT_EMPLOYEE = "HIDE_EDIT_EMPLOYEE";

export const SHOW_REGISTER_EMPLOYEE = "SHOW_REGISTER_EMPLOYEE";
export const HIDE_REGISTER_EMPLOYEE = "HIDE_REGISTER_EMPLOYEE";

export const SHOW_EXPORT_EXCEL = "SHOW_EXPORT_EXCEL";
export const HIDE_EXPORT_EXCEL = "HIDE_EXPORT_EXCEL";

export const SHOW_CHECK_CARD = "SHOW_CHECK_CARD";
export const HIDE_CHECK_CARD = "HIDE_CHECK_CARD";

export const SHOW_COMMENT_EMPLOYEE = "SHOW_COMMENT_EMPLOYEE";
export const HIDE_COMMENT_EMPLOYEE = "HIDE_COMMENT_EMPLOYEE";

export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS";

export const SHOW_NOTIFICATIONS = "SHOW_NOTIFICATIONS";
export const HIDE_NOTIFICATIONS = "HIDE_NOTIFICATIONS";

export const SHOW_PROCESS_NOTIFICATION = "SHOW_PROCESS_NOTIFICATION";
export const HIDE_PROCESS_NOTIFICATION = "HIDE_PROCESS_NOTIFICATION";

export const SHOW_HISTORY = "SHOW_HISTORY";
export const HIDE_HISTORY = "HIDE_HISTORY";
