export const LOG_EDIT_WORK_LOG = "LOG_EDIT_WORK_LOG";
export const LOG_SET_WORKING = "LOG_SET_WORKING";
export const LOG_SET_NOT_WORKING = "LOG_SET_NOT_WORKING";
export const LOG_EDIT_EMPLOYEE = "LOG_EDIT_EMPLOYEE";
export const LOG_ADD_EMPLOYEE = "LOG_ADD_EMPLOYEE";